[package]
name = "layers"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[toolchain]
channel = "nightly"

[lib]
crate-type = ["lib", "cdylib"] # Creates dynamic lib

[dependencies]
gl-rs = { package = "gl", version = "0.14.0" }
foreign-types-shared = "0.1.1"
indexmap = { version = "1.9.1", features = ["rayon"] }
indextree = { version = "4.5.0", features = ["par_iter"] }
rayon = "1.5.3"
libm = "0.2.2"
bitflags = "1.3"
paste = "1.0"
enum_dispatch = "0"

[dependencies.skia-safe]
version = "0"
# git = "https://github.com/rust-skia/rust-skia"
# tag = "0.56.0"
features = [
    "binary-cache",
    "embed-icudtl",
    "textlayout",
    "egl",
    "gl",
    "wayland",
]
# other features ["egl", "wayland"]

[dev-dependencies]
criterion = "0.3"
paste = "1.0"

[[bench]]
name = "my_benchmark"
harness = false

[build-dependencies]
cbindgen = "0.24.3"

[workspace]
members = ["examples/hello-rust"]
