[package]
name = "hello"
version = "0.1.0"
edition = "2021"
build = "build.rs"


# [lib]
# name = "hello"
# crate-type = ["cdylib"]      # Creates dynamic lib
# crate-type = ["staticlib"] # Creates static lib

[features]
gl = ["gpu", "skia-bindings/gl"]
egl = ["gl", "skia-bindings/egl"]
wayland = ["egl", "skia-safe/wayland"]
embed-freetype = ["skia-bindings/embed-freetype"]


gpu = []

[dependencies]
glutin = "0.28"
gl-rs = { package = "gl", version = "0.14.0" }
skia-safe = { version = "0.50", features = ["egl", "wayland"] }
skia-bindings = { version = "0", features = ["embed-freetype"] }
winit = "0.26.1"
foreign-types-shared = "0.1.1"
indexmap = { version = "1.9.1", features = ["rayon"] }
indextree = { version = "4.5.0", features = ["par_iter"] }
rand = "0.8.5"
rayon = "1.5.3"
libm = "0.2.2"
enum_dispatch = "0"
bitflags = "1.3"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "my_benchmark"
harness = false

[build-dependencies]
cbindgen = "0.24.3"
