[package]
name = "hello"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[lib]
crate-type = ["lib", "cdylib"] # Creates dynamic lib

[[bin]]
name = "hello"
path = "src/example.rs"

gpu = []

[dependencies]
glutin = "0.28"
gl-rs = { package = "gl", version = "0.14.0" }
winit = "0.26.1"
foreign-types-shared = "0.1.1"
indexmap = { version = "1.9.1", features = ["rayon"] }
indextree = { version = "4.5.0", features = ["par_iter"] }
rand = "0.8.5"
rayon = "1.5.3"
libm = "0.2.2"
enum_dispatch = "0"
bitflags = "1.3"
paste = "1.0"
# libc = { version = "0.2.137", features = ["use_std"] }

# [target.'cfg(target_os = "linux")'.features]
# skia-safe = ["egl", "wayland", "textlayout"]

# skia-bindings = { version = "0", features = ["binary-cache"] }

[dependencies.skia-safe]
git="https://github.com/rust-skia/rust-skia"
tag = "0.56.0"
features = ["gl", "textlayout"]

[features]
# gpu = []
# metal = ["gpu", "skia-bindings/metal"]
# textlayout = ["skia-bindings/textlayout"]
# gl = ["gpu", "skia-bindings/gl"]
# egl = ["gl", "skia-bindings/egl"]
# wayland = ["egl", "skia-bindings/wayland"]
# embed-icudtl = ["skia-bindings/embed-icudtl"]
# embed-freetype = ["skia-bindings/embed-freetype"]
# [target.'cfg(target_os = "macos")'.features]
# skia-safe = ["gl", "textlayout"]
# skia-bindings = ["binary-cache"]

[dev-dependencies]
criterion = "0.3"
paste = "1.0"

[[bench]]
name = "my_benchmark"
harness = false

[build-dependencies]
cbindgen = "0.24.3"
