[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
gpu = [ "skia-safe/gpu" ]
metal = [ "gpu", "skia-safe/metal" ]


[dependencies]
glutin = "0.28"
gl-rs = { package = "gl", version = "0.14.0" }
skia-safe = {version = "0", features = ["gl"]}
# skia-bindings = {version = "0", features = ["metal"], path = "../rust-skia/skia-bindings"}
winit = "0.26.1"
foreign-types-shared = "0.1.1"
# bevy_ecs = "0.8.0-dev"
indexmap = {version = "1.9.1", features = ["rayon"]}
rand = "0.8.5"
rayon = "1.5.3"
libm = "0.2.2"
enum_dispatch = "0"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "my_benchmark"
harness = false