[package]
name = "layers"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib", "cdylib"] # Creates dynamic lib

[dependencies]
gl-rs = { package = "gl", version = "0.14.0" }
foreign-types-shared = "0.1.1"
indexmap = { version = "1.9.1", features = ["rayon"] }
indextree = { version = "4.5.0", features = ["par_iter"] }
rayon = "1.5.3"
libm = "0.2.2"
bitflags = "1.3"
paste = "1.0"
enum_dispatch = "0"
oklab = "1.0.0"
taffy = "0.3.18"
diff-struct = "0.5.1"
derive_builder = "0.12.0"

[dependencies.skia-safe]
version = "0.62"

# this set of features is required for enabling to use the pre-built
# binaries of skia-safe
features = [
    "binary-cache",
    "egl",
    "gl",
    "svg",
    "textlayout",
    "vulkan",
    "wayland",
    "webp",
    "x11",
]

[dev-dependencies]
criterion = "0.3"
paste = "1.0"

[features]
export-skia = []
export-taffy = []

[[bench]]
name = "my_benchmark"
harness = false

[build-dependencies]
cbindgen = "0.24.3"

[workspace]
members = [
    "packages/layers-dsl",
    "packages/layers-dsl-core",
    "examples/hello-rust",
    "examples/hello-dom",
    "examples/hello-dsl",
    "examples/hello-content",
]
