[package]
name = "layers-debug-server"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.28", features = ["macros", "sync", "rt-multi-thread"] }
tokio-stream = "0.1.14"
warp = "0.3"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
futures = { version = "0.3", default-features = false }
static_dir = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
